import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
export const metadata = {
  title: "TerraMore Paginas UE",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
