import { Barlow_Condensed } from "next/font/google";
import "./globals.css";

// 1. Barlow Condensed font ko initialize karein
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "700", "900"], // Regular, Bold, aur Black weights
  variable: "--font-barlow-condensed", // Tailwind ke liye variable (optional)
});

export const metadata = {
  title: "TerraMore Paginas UE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      {/* 2. body tag mein barlowCondensed.className add karein */}
      <body className={`${barlowCondensed.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
